### A simple get request to the test endpoint. No need for login
GET {{url}}/auth/test/

### Create a new user - this one will only get a USER role by default
POST {{url}}/auth/register/

{
    "username": "user",
    "password": "test123"
}

###
POST {{url}}/auth/login/

{
    "username": "user",
    "password": "test123"
}

> {%
    client.global.set("jwt_token", response.body.token);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

###
GET {{url}}/protected/user_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

###
GET {{url}}/protected/admin_demo/
Accept: application/json
Authorization: Bearer {{jwt_token}}

### Add admin role to user
POST {{url}}/auth/user/addrole/
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
    "role": "superman"
}
Accept: application/json
Authorization: Bearer {{jwt_token}}

### UPDATE
PUT  {{url}}/quiz/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "question": "Hvad hedder den græske gud for solen?",
  "difficultyType": "MEDIUM",
  "options": [
    {
      "answerText": "Zeus",
      "correct": false
    },
    {
      "answerText": "Apollo",
      "correct": true
    },
    {
      "answerText": "Hades",
      "correct": false
    },
    {
      "answerText": "Hera",
      "correct": false
    }
  ]
}

### GET request with a header
GET {{url}}/quiz/2
Accept: application/json

### DELETE
DELETE {{url}}/quiz/2
Accept: application/json
Authorization: Bearer {{jwt_token}}

### POST example
POST {{url}}/quiz/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

{
  "question": "Hvad er det kemiske symbol for guld?",
  "difficultyType": "MEDIUM",
  "options": [
    {
      "answerText": "A: Ag",
      "correct": false
    },
    {
      "answerText": "B: Au",
      "correct": true
    },
    {
      "answerText": "C: Fe",
      "correct": false
    },
    {
      "answerText": "D: Pt",
      "correct": false
    }
  ]
}

### POST example with multiple entries
POST {{url}}/quiz/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt_token}}

[
  {
    "question": "Hvad er hovedstaden i Danmark?",
    "difficultyType": "EASY",
    "options": [
      {
        "answerText": "A: Stockholm",
        "correct": false
      },
      {
        "answerText": "B: Oslo",
        "correct": false
      },
      {
        "answerText": "C: København",
        "correct": true
      },
      {
        "answerText": "D: Helsinki",
        "correct": false
      }
    ]
  },
  {
    "question": "Hvilket dyr siger 'muh'?",
    "difficultyType": "EASY",
    "options": [
      {
        "answerText": "A: Hund",
        "correct": false
      },
      {
        "answerText": "B: Kat",
        "correct": false
      },
      {
        "answerText": "C: Ko",
        "correct": true
      },
      {
        "answerText": "D: Fugl",
        "correct": false
      }
    ]
  },
  {
    "question": "Hvilken planet er tættest på solen?",
    "difficultyType": "MEDIUM",
    "options": [
      {
        "answerText": "A: Mars",
        "correct": false
      },
      {
        "answerText": "B: Venus",
        "correct": false
      },
      {
        "answerText": "C: Merkur",
        "correct": true
      },
      {
        "answerText": "D: Jupiter",
        "correct": false
      }
    ]
  }
]

### Reset token
GET {{url}}/auth/test/

> {%
    client.global.set("jwt_token", null);
    console.log("JWT Token:", client.global.get("jwt_token"));
%}

### GET request with a header
GET {{url}}/poems/
Accept: application/json


